name = "kaga"
main = "_worker.js"
compatibility_date = "2023-08-23"

[unsafe.metadata.observability]
enabled = true

[observability.logs]
enabled = true
[[routes]]
pattern = "kaga.kaga.us.kg"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.kaga.us.kg"
custom_domain = true
